name: 'Deploy Plugin to Production'

on:
  push:
    branches: [ production ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:


      - name: Do a git checkout including submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Verify Workspace
        run: |
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"

      - name: Verify Folder
        run: |
          ls -lah ${GITHUB_WORKSPACE}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build it
        run: npm run build

      - name: Deploy to LezWatch.TV Production Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LWTV_SSH_KEY }}
          ARGS: "-rgoDzvc -i"
          REMOTE_HOST: ${{ secrets.LWTV_HOST }}
          REMOTE_USER: ${{ secrets.LWTV_USER }}
          TARGET: /home/${{ secrets.LWTV_USER }}/${{ secrets.LWTV_DOMAIN }}/wp-content/plugins/lwtv-plugin
          EXCLUDE: "/.git/, /.github/, /.husky/, /.vscode/, /node_scripts/, /node_modules/, /vendor/, .editorconfig, .gitignore, .npmrc, .nvmrc, composer.json, package-lock.json, package.json, phpcs.xml.dist, /blocks/node_modules/, /blocks/.editorconfig, /blocks/.gitignore, /blocks/package-lock.json, /blocks/package.json"

